Запускать нужно файл test_main.py

Причиной не правильного считывания веса был единовреммный опрос порта старого демона и кода main_feeder.py. Сейчас я выключил демон и вес передается норамльно. 
Я перенес значения offset и scale из вашей последней калибровки.
Пример вывода следующий:
2023-05-07 23:01:41.525 | INFO     | __main__:main:20 - Weight is: -0.31

2023-05-07 23:01:42.543 | INFO     | __main__:main:20 - Weight is: -0.31

2023-05-07 23:01:43.558 | INFO     | __main__:main:20 - Weight is: -0.31

2023-05-07 23:01:44.573 | INFO     | __main__:main:20 - Weight is: -0.31

2023-05-07 23:01:45.589 | INFO     | __main__:main:20 - Weight is: -0.31

Считаю, что проблем с весом нет. 
Чтобы окончательно проверить правильность передачи измерении веса запустите код и загружайте кормушку весом. Вес должен изменяться. 